<?php
require 'controlador_agenda.php';

if (isset($_GET['buscar']) and !empty($_GET['buscar'])){
    $meusContatos = buscarContato_nome($_GET['buscar']);
} else {
    $meusContatos = pegarContatos();
}
?>

<?php
session_start();
if(!isset($_SESSION['usuario_online']) OR !($_SESSION['usuario_online'] == true) ){
    header('Location: login.php');
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Agenda</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>


<div class="container" style="margin-top: 30px;">

    <h3>MINHA AGENDA DE CONTATOS</h3>
    <br />

    <!-- CADASTRO-->
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" method="post" action="controlador_agenda.php?acao=cadastrar">

                <!--nome-->
                <div class="form-group">
                    <label for="nome">Nome</label>
                    <input name="nome" type="text" class="form-control" id="nome">
                </div>

                <!--email-->
                <div class="form-group">
                    <label for="email">Email</label>
                    <input name="email" type="email" class="form-control" id="email">
                </div>

                <!--telefone-->
                <div class="form-group">
                    <label for="telefone">Telefone</label>
                    <input name="telefone" type="text" class="form-control" id="telefone">
                </div>

                <button type="submit" class="btn btn-default">CADASTRAR</button>

            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" method="get" action="">
                <div class="form-group">

                <input type="text" name="buscar" class="form-control" placeholder="Digite o Nome do Sujeito">
                </div>
                <button type="submit" class="btn btn-info">Buscar<span class="glyphicon glyphicon-search"></span></button>

                <a href="logout.php" class="btn btn-danger">Logout <span class="glyphicon glyphicon-remove"></span></a>

            </form>
        </div>
    </div>

    <br />

    <!--CONTATOS-->
    <div class="row">
        <div class="col-md-12">

            <!-- Conteúdo -->
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Telefone</th>
                    <th>acoes</th>
                </tr>
                </thead>
                <tbody>
                <!-- repetir -->
                <?php foreach($meusContatos as $contato): ?>
                    <tr>
                        <td><?= $contato['id'] ?></td>
                        <td><?= $contato['nome'] ?></td>
                        <td><?= $contato['email'] ?></td>
                        <td><?= $contato['telefone'] ?></td>
                        <td>
                            <a href="controlador_agenda.php?acao=excluir&id=<?= $contato['id'] ?>" class="btn btn-warning"> excluir </a>
                            <a href="editar.php?id=<?= $contato['id'] ?>" class="btn btn-primary">editar</a>
                        </td>
                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>